development:
  adapter: mysql2
  database: facebook_development
  pool: 5
  timeout: 5000
  username: root
  password: zainb
  host: localhost

test:
  adapter: mysql2
  database: facebook_test
  pool: 5
  timeout: 5000
  username: root
  password: zainb
  host: localhost

production:
  adapter: mysql2
  database: facebook_production
  pool: 5
  timeout: 5000
  username: root
  password: zainb
  host: localhost
